// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class BluditTestSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void adoAddContent() {
    driver.get("http://localhost:8080/administrator/");
    driver.manage().window().setSize(new Dimension(1200, 700));
    System.out.println("{ASSESSOR}:LoginPO:doLogin");
    driver.findElement(By.name("username")).sendKeys("admin");
    driver.findElement(By.name("password")).sendKeys("password");
    driver.findElement(By.cssSelector(".uk-button")).click();
    System.out.println("{ASSESSOR}:HomePO:goToNewContent");
    driver.findElement(By.linkText("New content")).click();
    System.out.println("{ASSESSOR}:NewContentPO:createNewContent");
    driver.findElement(By.id("jstitle")).sendKeys("Test content");
    driver.findElement(By.cssSelector(".uk-button:nth-child(1)")).click();
    System.out.println("{ASSESSOR}:ContentPO:getContentTitle");
    {
      List<WebElement> elements = driver.findElements(By.linkText("Test content"));
      assert(elements.size() > 0);
    }
    System.out.println("{ASSESSOR}:HomePO:logout");
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.linkText("Log out")));
    }
    driver.findElement(By.linkText("Log out")).click();
  }
  @Test
  public void bdoChangeUrl() {
    driver.get("http://localhost:8080/administrator/");
    driver.manage().window().setSize(new Dimension(1200, 700));
    System.out.println("{ASSESSOR}:LoginPO:doLogin");
    driver.findElement(By.name("username")).sendKeys("admin");
    driver.findElement(By.name("password")).sendKeys("password");
    driver.findElement(By.cssSelector(".uk-button")).click();
    System.out.println("{ASSESSOR}:HomePO:goToContent");
    driver.findElement(By.linkText("Content")).click();
    System.out.println("{ASSESSOR}:ContentPO:changeUrl");
    driver.findElement(By.linkText("Test content")).click();
    driver.findElement(By.cssSelector("li:nth-child(7) > .sidebar-button")).click();
    driver.findElement(By.id("jsslug")).sendKeys("new-post-url");
    driver.findElement(By.cssSelector(".uk-button:nth-child(1)")).click();
    System.out.println("{ASSESSOR}:HomePO:goToContent");
    driver.findElement(By.linkText("Content")).click();
    System.out.println("{ASSESSOR}:ContentPO:getContentUrl");
    {
      List<WebElement> elements = driver.findElements(By.linkText("/new-post-url"));
      assert(elements.size() > 0);
    }
    System.out.println("{ASSESSOR}:HomePO:logout");
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.linkText("Log out")));
    }
    driver.findElement(By.linkText("Log out")).click();
  }
  @Test
  public void cdoChangePosition() {
    driver.get("http://localhost:8080/administrator/");
    driver.manage().window().setSize(new Dimension(1200, 700));
    System.out.println("{ASSESSOR}:LoginPO:doLogin");
    driver.findElement(By.name("username")).sendKeys("admin");
    driver.findElement(By.name("password")).sendKeys("password");
    driver.findElement(By.cssSelector(".uk-button")).click();
    System.out.println("{ASSESSOR}:HomePO:goToContent");
    driver.findElement(By.linkText("Content")).click();
    System.out.println("{ASSESSOR}:ContentPO:changeContentPosition");
    driver.findElement(By.linkText("Test content")).click();
    driver.findElement(By.cssSelector("li:nth-child(7) > .sidebar-button")).click();
    driver.findElement(By.id("jsposition")).sendKeys("30");
    driver.findElement(By.cssSelector(".uk-button:nth-child(1)")).click();
    System.out.println("{ASSESSOR}:HomePO:goToContent");
    driver.findElement(By.linkText("Content")).click();
    System.out.println("{ASSESSOR}:ContentPO:getContentPosition");
    driver.findElement(By.linkText("Test content")).click();
    driver.findElement(By.cssSelector("li:nth-child(7) > .sidebar-button")).click();
    {
      String value = driver.findElement(By.id("jsposition")).getAttribute("value");
      assertThat(value, is("30"));
    }
    System.out.println("{ASSESSOR}:HomePO:logout");
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.linkText("Log out")));
    }
    driver.findElement(By.linkText("Log out")).click();
  }
  @Test
  public void ddoChangeParent() {
    driver.get("http://localhost:8080/administrator/");
    driver.manage().window().setSize(new Dimension(1200, 700));
    System.out.println("{ASSESSOR}:LoginPO:doLogin");
    driver.findElement(By.name("username")).sendKeys("admin");
    driver.findElement(By.name("password")).sendKeys("password");
    driver.findElement(By.cssSelector(".uk-button")).click();
    System.out.println("{ASSESSOR}:HomePO:goToContent");
    driver.findElement(By.linkText("Content")).click();
    System.out.println("{ASSESSOR}:ContentPO:changeContentParent");
    driver.findElement(By.linkText("Test content")).click();
    driver.findElement(By.cssSelector("li:nth-child(7) > .sidebar-button")).click();
    {
      WebElement dropdown = driver.findElement(By.id("jsparent"));
      dropdown.findElement(By.xpath("//option[. = 'Create your own content']")).click();
    }
    driver.findElement(By.cssSelector(".uk-button:nth-child(1)")).click();
    System.out.println("{ASSESSOR}:HomePO:goToContent");
    driver.findElement(By.linkText("Content")).click();
    System.out.println("{ASSESSOR}:ContentPO:getContentParent");
    driver.findElement(By.linkText("Test content")).click();
    driver.findElement(By.cssSelector("li:nth-child(7) > .sidebar-button")).click();
    {
      String value = driver.findElement(By.id("jsparent")).getAttribute("value");
      assertThat(value, is("create-your-own-content"));
    }
    System.out.println("{ASSESSOR}:HomePO:logout");
    driver.findElement(By.cssSelector(".bl-navbar-right")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.linkText("Log out")));
    }
    driver.findElement(By.linkText("Log out")).click();
  }
  @Test
  public void edoAddContentAsDraft() {
    driver.get("http://localhost:8080/administrator/");
    driver.manage().window().setSize(new Dimension(1200, 700));
    System.out.println("{ASSESSOR}:LoginPO:doLogin");
    driver.findElement(By.name("username")).sendKeys("admin");
    driver.findElement(By.name("password")).sendKeys("password");
    driver.findElement(By.cssSelector(".uk-button")).click();
    System.out.println("{ASSESSOR}:HomePO:goToNewContent");
    driver.findElement(By.linkText("New content")).click();
    System.out.println("{ASSESSOR}:NewContentPO:createContentAsDraft");
    driver.findElement(By.id("jstitle")).sendKeys("Draft Content");
    driver.findElement(By.id("jsSaveDraft")).click();
    System.out.println("{ASSESSOR}:ContentPO:getDraftContentTitle");
    {
      List<WebElement> elements = driver.findElements(By.linkText("Draft Content"));
      assert(elements.size() > 0);
    }
    System.out.println("{ASSESSOR}:HomePO:logout");
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.linkText("Log out")));
    }
    driver.findElement(By.linkText("Log out")).click();
  }
  @Test
  public void fdoSetContentAsSticky() {
    driver.get("http://localhost:8080/administrator/");
    driver.manage().window().setSize(new Dimension(1200, 700));
    System.out.println("{ASSESSOR}:LoginPO:doLogin");
    driver.findElement(By.name("username")).sendKeys("admin");
    driver.findElement(By.name("password")).sendKeys("password");
    driver.findElement(By.cssSelector(".uk-button")).click();
    System.out.println("{ASSESSOR}:HomePO:goToContent");
    driver.findElement(By.linkText("Content")).click();
    System.out.println("{ASSESSOR}:ContentPO:setContentAsStickyPost");
    driver.findElement(By.linkText("Set up your new site")).click();
    driver.findElement(By.cssSelector("li:nth-child(7) > .sidebar-button")).click();
    {
      WebElement dropdown = driver.findElement(By.id("jsstatus"));
      dropdown.findElement(By.xpath("//option[. = 'Sticky']")).click();
    }
    driver.findElement(By.cssSelector(".uk-button:nth-child(1)")).click();
    System.out.println("{ASSESSOR}:HomePO:goToContent");
    driver.findElement(By.linkText("Content")).click();
    System.out.println("{ASSESSOR}:ContentPO:getStickyContentTitle");
    {
      List<WebElement> elements = driver.findElements(By.linkText("Set up your new site"));
      assert(elements.size() > 0);
    }
    System.out.println("{ASSESSOR}:HomePO:logout");
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.linkText("Log out")));
    }
    driver.findElement(By.linkText("Log out")).click();
  }
  @Test
  public void gdoDeleteContent() {
    driver.get("http://localhost:8080/administrator/");
    driver.manage().window().setSize(new Dimension(1200, 700));
    System.out.println("{ASSESSOR}:LoginPO:doLogin");
    driver.findElement(By.name("username")).sendKeys("admin");
    driver.findElement(By.name("password")).sendKeys("password");
    driver.findElement(By.cssSelector(".uk-button")).click();
    System.out.println("{ASSESSOR}:HomePO:goToContent");
    driver.findElement(By.linkText("Content")).click();
    System.out.println("{ASSESSOR}:ContentPO:deleteContent");
    driver.findElement(By.linkText("Follow Bludit")).click();
    driver.findElement(By.id("jsdelete")).click();
    driver.switchTo().alert().accept();
    {
      List<WebElement> elements = driver.findElements(By.linkText("Follow Bludit"));
      assert(elements.size() == 0);
    }
    System.out.println("{ASSESSOR}:HomePO:logout");
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.linkText("Log out")));
    }
    driver.findElement(By.linkText("Log out")).click();
  }
  @Test
  public void hdoAddUser() {
    driver.get("http://localhost:8080/administrator/");
    driver.manage().window().setSize(new Dimension(1200, 700));
    System.out.println("{ASSESSOR}:LoginPO:doLogin");
    driver.findElement(By.name("username")).sendKeys("admin");
    driver.findElement(By.name("password")).sendKeys("password");
    driver.findElement(By.cssSelector(".uk-button")).click();
    System.out.println("{ASSESSOR}:HomePO:goToUsers");
    driver.findElement(By.linkText("Users")).click();
    System.out.println("{ASSESSOR}:UsersPO:createNewUser");
    driver.findElement(By.linkText("Add a new user")).click();
    driver.findElement(By.id("jsnew_username")).sendKeys("usertest");
    driver.findElement(By.id("jsnew_password")).sendKeys("usertest123");
    driver.findElement(By.id("jsconfirm_password")).sendKeys("usertest123");
    {
      WebElement dropdown = driver.findElement(By.id("jsrole"));
      dropdown.findElement(By.xpath("//option[. = 'Administrator']")).click();
    }
    driver.findElement(By.cssSelector(".uk-button-primary")).click();
    System.out.println("{ASSESSOR}:UsersPO:getUserUsername");
    {
      List<WebElement> elements = driver.findElements(By.linkText("usertest"));
      assert(elements.size() > 0);
    }
    System.out.println("{ASSESSOR}:HomePO:logout");
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.linkText("Log out")));
    }
    driver.findElement(By.linkText("Log out")).click();
  }
  @Test
  public void idoChangePassword() {
    driver.get("http://localhost:8080/administrator/");
    driver.manage().window().setSize(new Dimension(1200, 700));
    System.out.println("{ASSESSOR}:LoginPO:doLogin");
    driver.findElement(By.name("username")).sendKeys("admin");
    driver.findElement(By.name("password")).sendKeys("password");
    driver.findElement(By.cssSelector(".uk-button")).click();
    System.out.println("{ASSESSOR}:HomePO:goToUsers");
    driver.findElement(By.linkText("Users")).click();
    System.out.println("{ASSESSOR}:UsersPO:changeUserPassword");
    driver.findElement(By.linkText("usertest")).click();
    driver.findElement(By.linkText("Change password")).click();
    driver.findElement(By.id("jsnew_password")).sendKeys("newpassword");
    driver.findElement(By.id("jsconfirm_password")).sendKeys("newpassword");
    driver.findElement(By.cssSelector(".uk-button-primary")).click();
    System.out.println("{ASSESSOR}:HomePO:getAlert");
    {
      List<WebElement> elements = driver.findElements(By.id("alert"));
      assert(elements.size() > 0);
    }
    System.out.println("{ASSESSOR}:HomePO:logout");
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.linkText("Log out")));
    }
    driver.findElement(By.linkText("Log out")).click();
  }
  @Test
  public void jdoAddSocials() {
    driver.get("http://localhost:8080/administrator/");
    driver.manage().window().setSize(new Dimension(1200, 700));
    System.out.println("{ASSESSOR}:LoginPO:doLogin");
    driver.findElement(By.name("username")).sendKeys("admin");
    driver.findElement(By.name("password")).sendKeys("password");
    driver.findElement(By.cssSelector(".uk-button")).click();
    System.out.println("{ASSESSOR}:HomePO:goToUsers");
    driver.findElement(By.linkText("Users")).click();
    System.out.println("{ASSESSOR}:UsersPO:addSocialMediaToUser");
    driver.findElement(By.linkText("admin")).click();
    driver.findElement(By.id("jsfacebook")).sendKeys("https://www.facebook.com/some_fake_user_name_52432562135863");
    driver.findElement(By.id("jsinstagram")).sendKeys("https://instagram.com/some_fake_user_name_52432562135863");
    driver.findElement(By.cssSelector(".uk-button-primary")).click();
    System.out.println("{ASSESSOR}:HomePO:goToUsers");
    driver.findElement(By.linkText("Users")).click();
    System.out.println("{ASSESSOR}:UsersPO:getUserSocialMedia");
    driver.findElement(By.linkText("admin")).click();
    {
      String value = driver.findElement(By.id("jsfacebook")).getAttribute("value");
      assertThat(value, is("https://www.facebook.com/some_fake_user_name_52432562135863"));
    }
    {
      String value = driver.findElement(By.id("jsinstagram")).getAttribute("value");
      assertThat(value, is("https://instagram.com/some_fake_user_name_52432562135863"));
    }
    System.out.println("{ASSESSOR}:HomePO:logout");
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.linkText("Log out")));
    }
    driver.findElement(By.linkText("Log out")).click();
  }
}
