package TestCases;

import org.junit.*;
// Generated by Selenium IDE

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.junit.runners.MethodSorters;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

import TestCases.PO.*;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class TestCases {

    @BeforeClass()
    public static void setup() {
    }

    private WebDriver driver;

    private Map<String, Object> vars;

    private JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void a_addNewProduct() {
        LoginPO _LoginPO = new LoginPO(driver, js, vars);
        _LoginPO.doLogin("admin@prestashop.com", "password");
        DashboardPO _DashboardPO = new DashboardPO(driver, js, vars);
        _DashboardPO.doAddNewProduct("Blue Jacket3");
        assert (_DashboardPO.set_CSSSELECTOR_alert_successnth_child1().size() > 0);
        _DashboardPO.doLogout();
    }

    @Test
    public void b_addEmptyProduct() {
        LoginPO _LoginPO = new LoginPO(driver, js, vars);
        _LoginPO.doLogin("admin@prestashop.com", "password");
        DashboardPO _DashboardPO = new DashboardPO(driver, js, vars);
        _DashboardPO.doAddEmptyProduct();
        assertThat(_DashboardPO.set_CSSSELECTOR_ollinth_child1_1(), is("This link_rewrite field is required at least in English (English)"));
        assertThat(_DashboardPO.set_CSSSELECTOR_ollinth_child2(), is("This name field is required at least in English (English)"));
        _DashboardPO.doLogout();
    }

    @Test
    public void c_editProduct() {
        LoginPO _LoginPO = new LoginPO(driver, js, vars);
        _LoginPO.doLogin("admin@prestashop.com", "password");
        DashboardPO _DashboardPO = new DashboardPO(driver, js, vars);
        _DashboardPO.doEditProduct("Deep Blue Jacket");
        assert (_DashboardPO.set_CSSSELECTOR_alert_successnth_child1().size() > 0);
        _DashboardPO.doLogout();
    }

    @Test
    public void d_addNewState() {
        LoginPO _LoginPO = new LoginPO(driver, js, vars);
        _LoginPO.doLogin("admin@prestashop.com", "password");
        DashboardPO _DashboardPO = new DashboardPO(driver, js, vars);
        _DashboardPO.doAddNewState("Liguria", "1121", "Italy", "Europe");
        assert (_DashboardPO.set_CSSSELECTOR_alert_successnth_child1().size() > 0);
        _DashboardPO.doLogout();
    }

    @Test
    public void e_addEmptyState() {
        LoginPO _LoginPO = new LoginPO(driver, js, vars);
        _LoginPO.doLogin("admin@prestashop.com", "password");
        DashboardPO _DashboardPO = new DashboardPO(driver, js, vars);
        _DashboardPO.doAddEmptyState();
        assertThat(_DashboardPO.set_CSSSELECTOR_ollinth_child1_1(), is("The iso_code field is required."));
        _DashboardPO.click_CSSSELECTOR_ollinth_child2();
    }

    @Test
    public void f_addNewFeature() {
        LoginPO _LoginPO = new LoginPO(driver, js, vars);
        _LoginPO.doLogin("admin@prestashop.com", "password");
        DashboardPO _DashboardPO = new DashboardPO(driver, js, vars);
        _DashboardPO.doAddNewFeature("Strong");
        assert (_DashboardPO.set_CSSSELECTOR_alert_successnth_child1().size() > 0);
        _DashboardPO.doLogout();
    }

    @Test
    public void g_addEmptyFeature() {
        LoginPO _LoginPO = new LoginPO(driver, js, vars);
        _LoginPO.doLogin("admin@prestashop.com", "password");
        DashboardPO _DashboardPO = new DashboardPO(driver, js, vars);
        _DashboardPO.doAddEmptyFeature();
        assert (_DashboardPO.set_CSSSELECTOR_alert_danger().size() > 0);
        _DashboardPO.doLogout();
    }

    @Test
    public void h_addNewAttribute() {
        LoginPO _LoginPO = new LoginPO(driver, js, vars);
        _LoginPO.doLogin("admin@prestashop.com", "password");
        DashboardPO _DashboardPO = new DashboardPO(driver, js, vars);
        _DashboardPO.doAddNewAttribute("Quantity", "Qnt");
        assert (_DashboardPO.set_CSSSELECTOR_alert_successnth_child1().size() > 0);
        _DashboardPO.doLogout();
    }
}
