// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PrestashopTestSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addNewProduct() {
    System.out.println("{ASSESSOR}:LoginPO:doLogin");
    driver.get("http://localhost:8080/administrator/");
    driver.manage().window().setSize(new Dimension(1174, 825));
    driver.findElement(By.id("email")).sendKeys("admin@prestashop.com");
    driver.findElement(By.id("passwd")).sendKeys("password");
    driver.findElement(By.name("submitLogin")).click();
    System.out.println("{ASSESSOR}:DashboardPO:doAddNewProduct");
    {
      WebElement element = driver.findElement(By.linkText("Catalog"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Products")).click();
    driver.findElement(By.id("page-header-desc-product-new_product")).click();
    driver.findElement(By.id("name_1")).sendKeys("Blue Jacket3");
    driver.findElement(By.name("submitAddproduct")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert-success:nth-child(1)"));
      assert(elements.size() > 0);
    }
    System.out.println("{ASSESSOR}:DashboardPO:doLogout");
    driver.findElement(By.cssSelector(".employee_name")).click();
    driver.findElement(By.id("header_logout")).click();
  }
  @Test
  public void addEmptyProduct() {
    System.out.println("{ASSESSOR}:LoginPO:doLogin");
    driver.get("http://localhost:8080/administrator/");
    driver.manage().window().setSize(new Dimension(1174, 825));
    driver.findElement(By.id("email")).sendKeys("admin@prestashop.com");
    driver.findElement(By.id("passwd")).sendKeys("password");
    driver.findElement(By.name("submitLogin")).click();
    System.out.println("{ASSESSOR}:DashboardPO:doAddEmptyProduct");
    {
      WebElement element = driver.findElement(By.linkText("Catalog"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Products")).click();
    driver.findElement(By.id("page-header-desc-product-new_product")).click();
    driver.findElement(By.name("submitAddproduct")).click();
    assertThat(driver.findElement(By.cssSelector("ol > li:nth-child(1)")).getText(), is("This link_rewrite field is required at least in English (English)"));
    assertThat(driver.findElement(By.cssSelector("ol > li:nth-child(2)")).getText(), is("This name field is required at least in English (English)"));
    System.out.println("{ASSESSOR}:DashboardPO:doLogout");
    driver.findElement(By.cssSelector(".employee_name")).click();
    driver.findElement(By.id("header_logout")).click();
  }
  @Test
  public void editProduct() {
    System.out.println("{ASSESSOR}:LoginPO:doLogin");
    driver.get("http://localhost:8080/administrator/");
    driver.manage().window().setSize(new Dimension(1174, 825));
    driver.findElement(By.id("email")).sendKeys("admin@prestashop.com");
    driver.findElement(By.id("passwd")).sendKeys("password");
    driver.findElement(By.name("submitLogin")).click();
    System.out.println("{ASSESSOR}:DashboardPO:doEditProduct");
    {
      WebElement element = driver.findElement(By.linkText("Catalog"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Products")).click();
    driver.findElement(By.cssSelector("#tr__8_0 .edit")).click();
    driver.findElement(By.id("name_1")).sendKeys("Deep Blue Jacket");
    driver.findElement(By.name("submitAddproduct")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert-success:nth-child(1)"));
      assert(elements.size() > 0);
    }
    System.out.println("{ASSESSOR}:DashboardPO:doLogout");
    driver.findElement(By.cssSelector(".employee_name")).click();
    driver.findElement(By.id("header_logout")).click();
  }
  @Test
  public void addNewState() {
    System.out.println("{ASSESSOR}:LoginPO:doLogin");
    driver.get("http://localhost:8080/administrator/");
    driver.manage().window().setSize(new Dimension(1174, 825));
    driver.findElement(By.id("email")).sendKeys("admin@prestashop.com");
    driver.findElement(By.id("passwd")).sendKeys("password");
    driver.findElement(By.name("submitLogin")).click();
    System.out.println("{ASSESSOR}:DashboardPO:doAddNewState");
    {
      WebElement element = driver.findElement(By.linkText("Localization"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("States")).click();
    driver.findElement(By.id("page-header-desc-state-new_state")).click();
    driver.findElement(By.id("name")).sendKeys("Liguria");
    driver.findElement(By.id("iso_code")).sendKeys("1121");
    {
      WebElement dropdown = driver.findElement(By.id("id_country"));
      dropdown.findElement(By.xpath("//option[. = 'Italy']")).click();
    }
    {
      WebElement dropdown = driver.findElement(By.id("id_zone"));
      dropdown.findElement(By.xpath("//option[. = 'Europe']")).click();
    }
    driver.findElement(By.id("state_form_submit_btn")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert-success:nth-child(1)"));
      assert(elements.size() > 0);
    }
    System.out.println("{ASSESSOR}:DashboardPO:doLogout");
    driver.findElement(By.cssSelector(".employee_name")).click();
    driver.findElement(By.id("header_logout")).click();
  }
  @Test
  public void addEmptyState() {
    System.out.println("{ASSESSOR}:LoginPO:doLogin");
    driver.get("http://localhost:8080/administrator/");
    driver.manage().window().setSize(new Dimension(1174, 825));
    driver.findElement(By.id("email")).sendKeys("admin@prestashop.com");
    driver.findElement(By.id("passwd")).sendKeys("password");
    driver.findElement(By.name("submitLogin")).click();
    System.out.println("{ASSESSOR}:DashboardPO:doAddEmptyState");
    {
      WebElement element = driver.findElement(By.linkText("Localization"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("States")).click();
    driver.findElement(By.id("page-header-desc-state-new_state")).click();
    driver.findElement(By.id("state_form_submit_btn")).click();
    assertThat(driver.findElement(By.cssSelector("ol > li:nth-child(1)")).getText(), is("The iso_code field is required."));
    driver.findElement(By.cssSelector("ol > li:nth-child(2)")).click();
    System.out.println("{ASSESSOR}:DashboardPO:doLogout");
    driver.findElement(By.cssSelector(".employee_name")).click();
    driver.findElement(By.id("header_logout")).click();
  }
  @Test
  public void addNewFeature() {
    System.out.println("{ASSESSOR}:LoginPO:doLogin");
    driver.get("http://localhost:8080/administrator/");
    driver.manage().window().setSize(new Dimension(1174, 825));
    driver.findElement(By.id("email")).sendKeys("admin@prestashop.com");
    driver.findElement(By.id("passwd")).sendKeys("password");
    driver.findElement(By.name("submitLogin")).click();
    System.out.println("{ASSESSOR}:DashboardPO:doAddNewFeature");
    {
      WebElement element = driver.findElement(By.linkText("Catalog"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Product Features")).click();
    driver.findElement(By.id("page-header-desc-feature-new_feature")).click();
    driver.findElement(By.id("name_1")).sendKeys("Strong");
    driver.findElement(By.id("feature_form_submit_btn")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert-success:nth-child(1)"));
      assert(elements.size() > 0);
    }
    System.out.println("{ASSESSOR}:DashboardPO:doLogout");
    driver.findElement(By.cssSelector(".employee_name")).click();
    driver.findElement(By.id("header_logout")).click();
  }
  @Test
  public void addEmptyFeature() {
    System.out.println("{ASSESSOR}:LoginPO:doLogin");
    driver.get("http://localhost:8080/administrator/");
    driver.manage().window().setSize(new Dimension(1174, 825));
    driver.findElement(By.id("email")).sendKeys("admin@prestashop.com");
    driver.findElement(By.id("passwd")).sendKeys("password");
    driver.findElement(By.name("submitLogin")).click();
    System.out.println("{ASSESSOR}:DashboardPO:doAddEmptyFeature");
    {
      WebElement element = driver.findElement(By.linkText("Catalog"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Product Features")).click();
    driver.findElement(By.id("page-header-desc-feature-new_feature")).click();
    driver.findElement(By.id("feature_form_submit_btn")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert-danger"));
      assert(elements.size() > 0);
    }
    System.out.println("{ASSESSOR}:DashboardPO:doLogout");
    driver.findElement(By.cssSelector(".employee_name")).click();
    driver.findElement(By.id("header_logout")).click();
  }
  @Test
  public void addNewAttribute() {
    System.out.println("{ASSESSOR}:LoginPO:doLogin");
    driver.get("http://localhost:8080/administrator/");
    driver.manage().window().setSize(new Dimension(1174, 825));
    driver.findElement(By.id("email")).sendKeys("admin@prestashop.com");
    driver.findElement(By.id("passwd")).sendKeys("password");
    driver.findElement(By.name("submitLogin")).click();
    System.out.println("{ASSESSOR}:DashboardPO:doAddNewAttribute");
    {
      WebElement element = driver.findElement(By.linkText("Catalog"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Product Attributes")).click();
    driver.findElement(By.id("page-header-desc-attribute_group-new_attribute_group")).click();
    driver.findElement(By.id("name_1")).sendKeys("Quantity");
    driver.findElement(By.id("public_name_1")).sendKeys("Qnt");
    driver.findElement(By.id("attribute_group_form_submit_btn")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert-success:nth-child(1)"));
      assert(elements.size() > 0);
    }
    System.out.println("{ASSESSOR}:DashboardPO:doLogout");
    driver.findElement(By.cssSelector(".employee_name")).click();
    driver.findElement(By.id("header_logout")).click();
  }
}
