version: "3.8"

networks:
  my-network:

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: wordpress
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

  apache:
    image: httpd:2.4
    ports:
      - "80:80"
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - mysql
    networks:
      - my-network

  wordpress:
    image: wordpress:latest
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - my-network

volumes:
  mysql-data: {}
  wordpress: {}
