package TestCases;

import org.junit.BeforeClass;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import TestCases.PO.*;

public class TestCases {

    @BeforeClass()
    public static void setup() {
        System.setProperty("webdriver.gecko.driver", "InsertGeckoPathHere");
    }

    private WebDriver driver;

    private Map<String, Object> vars;

    private JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void adoAddNewProduct() {
        driver.get("http://localhost:8080/administrator");
        driver.manage().window().setSize(new Dimension(1200, 700));
        LoginPO _LoginPO = new LoginPO(driver, js, vars);
        _LoginPO.login("admin@prestashop.com", "password");
        HomePO _HomePO = new HomePO(driver, js, vars);
        _HomePO.goToProducts();
        ProductsPO _ProductsPO = new ProductsPO(driver, js, vars);
        _ProductsPO.addNewProduct("Blue Jacket3");
        assert (_ProductsPO.set_CSSSELECTOR_alert_successnth_child1().size() > 0);
        _HomePO.logout();
    }

    @Test
    public void bdoAddEmptyProduct() {
        driver.get("http://localhost:8080/administrator");
        driver.manage().window().setSize(new Dimension(1200, 700));
        LoginPO _LoginPO = new LoginPO(driver, js, vars);
        _LoginPO.login("admin@prestashop.com", "password");
        HomePO _HomePO = new HomePO(driver, js, vars);
        _HomePO.goToProducts();
        ProductsPO _ProductsPO = new ProductsPO(driver, js, vars);
        _ProductsPO.addNewEmptyProduct();
        assertThat(_ProductsPO.set_CSSSELECTOR_ollinth_child1_1(), is("This link_rewrite field is required at least in English (English)"));
        assertThat(_ProductsPO.set_CSSSELECTOR_ollinth_child2(), is("This name field is required at least in English (English)"));
        _HomePO.logout();
    }

    @Test
    public void cdoEditProduct() {
        driver.get("http://localhost:8080/administrator");
        driver.manage().window().setSize(new Dimension(1200, 700));
        LoginPO _LoginPO = new LoginPO(driver, js, vars);
        _LoginPO.login("admin@prestashop.com", "password");
        HomePO _HomePO = new HomePO(driver, js, vars);
        _HomePO.goToProducts();
        ProductsPO _ProductsPO = new ProductsPO(driver, js, vars);
        _ProductsPO.editProduct("Deep Blue Jacket");
        assert (_ProductsPO.set_CSSSELECTOR_alert_successnth_child1().size() > 0);
        _HomePO.logout();
    }

    @Test
    public void ddoAddNewState() {
        driver.get("http://localhost:8080/administrator");
        driver.manage().window().setSize(new Dimension(1200, 700));
        LoginPO _LoginPO = new LoginPO(driver, js, vars);
        _LoginPO.login("admin@prestashop.com", "password");
        HomePO _HomePO = new HomePO(driver, js, vars);
        _HomePO.goToStates();
        StatesPO _StatesPO = new StatesPO(driver, js, vars);
        _StatesPO.addNewState("Liguria", "1121", "Italy", "Europe");
        assert (_StatesPO.set_CSSSELECTOR_alert_successnth_child1().size() > 0);
        _HomePO.logout();
    }

    @Test
    public void edoAddEmptyState() {
        driver.get("http://localhost:8080/administrator");
        driver.manage().window().setSize(new Dimension(1200, 700));
        LoginPO _LoginPO = new LoginPO(driver, js, vars);
        _LoginPO.login("admin@prestashop.com", "password");
        HomePO _HomePO = new HomePO(driver, js, vars);
        _HomePO.goToStates();
        StatesPO _StatesPO = new StatesPO(driver, js, vars);
        _StatesPO.addEmptyState();
        assertThat(_StatesPO.set_CSSSELECTOR_ollinth_child1_1(), is("The iso_code field is required."));
        assertThat(_StatesPO.set_CSSSELECTOR_ollinth_child2(), is("The name field is required."));
        _HomePO.logout();
    }

    @Test
    public void fdoAddNewProductWithTax() {
        driver.get("http://localhost:8080/administrator");
        driver.manage().window().setSize(new Dimension(1200, 700));
        LoginPO _LoginPO = new LoginPO(driver, js, vars);
        _LoginPO.login("admin@prestashop.com", "password");
        HomePO _HomePO = new HomePO(driver, js, vars);
        _HomePO.goToProducts();
        ProductsPO _ProductsPO = new ProductsPO(driver, js, vars);
        _ProductsPO.addNewProductWithTax("10");
        assertThat(_ProductsPO.set_ID_priceTI(), is("12.20"));
        _HomePO.logout();
    }

    @Test
    public void gdoAddNewProductWithTax10() {
        driver.get("http://localhost:8080/administrator");
        driver.manage().window().setSize(new Dimension(1200, 700));
        LoginPO _LoginPO = new LoginPO(driver, js, vars);
        _LoginPO.login("admin@prestashop.com", "password");
        HomePO _HomePO = new HomePO(driver, js, vars);
        _HomePO.goToProducts();
        ProductsPO _ProductsPO = new ProductsPO(driver, js, vars);
        _ProductsPO.addNewProductWithTax10("10", "IT Reduced Rate (10%)");
        assertThat(_ProductsPO.set_ID_priceTI(), is("11.00"));
        _HomePO.logout();
    }

    @Test
    public void hdoAddNewFeature() {
        driver.get("http://localhost:8080/administrator");
        driver.manage().window().setSize(new Dimension(1200, 700));
        LoginPO _LoginPO = new LoginPO(driver, js, vars);
        _LoginPO.login("admin@prestashop.com", "password");
        HomePO _HomePO = new HomePO(driver, js, vars);
        _HomePO.goToProductFeatures();
        ProductFeaturesPO _ProductFeaturesPO = new ProductFeaturesPO(driver, js, vars);
        _ProductFeaturesPO.AddNewFeature("Strong");
        assert (_ProductFeaturesPO.set_CSSSELECTOR_alert_successnth_child1().size() > 0);
        _HomePO.logout();
    }

    @Test
    public void idoAddEmptyFeature() {
        driver.get("http://localhost:8080/administrator");
        driver.manage().window().setSize(new Dimension(1200, 700));
        LoginPO _LoginPO = new LoginPO(driver, js, vars);
        _LoginPO.login("admin@prestashop.com", "password");
        HomePO _HomePO = new HomePO(driver, js, vars);
        _HomePO.goToProductFeatures();
        ProductFeaturesPO _ProductFeaturesPO = new ProductFeaturesPO(driver, js, vars);
        _ProductFeaturesPO.AddEmptyFeature();
        assert (_ProductFeaturesPO.set_CSSSELECTOR_alert_danger().size() > 0);
        _HomePO.logout();
    }

    @Test
    public void jdoAddNewProductAttribute() {
        driver.get("http://localhost:8080/administrator");
        driver.manage().window().setSize(new Dimension(1200, 700));
        LoginPO _LoginPO = new LoginPO(driver, js, vars);
        _LoginPO.login("admin@prestashop.com", "password");
        HomePO _HomePO = new HomePO(driver, js, vars);
        _HomePO.goToProductAttributes();
        ProductAttributesPO _ProductAttributesPO = new ProductAttributesPO(driver, js, vars);
        _ProductAttributesPO.addNewAttribute("Quantity", "Qnt");
        assert (_ProductAttributesPO.set_CSSSELECTOR_alert_successnth_child1().size() > 0);
        _HomePO.logout();
    }
}
