networks:
  my-network: { }

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    platform: linux/amd64
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
    depends_on:
      - database
    networks:
      - my-network

  database:
    image: mysql:latest
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    networks:
      - my-network

  apache:
    platform: linux/amd64
    image: httpd:latest
    ports:
      - "8081:80"
    depends_on:
      - database
    networks:
      - my-network

  mongodb:
    image: mongo:4.4
    platform: linux/amd64
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "admin"
    ports:
      - "27017:27017"
    networks:
      - my-network