networks:
  test-vn: { }
  test-n: { }

services:
  vulnerable-wordpress:
    image: wordpress:4.8
    ports:
      - "8080:80"
    platform: linux/amd64
    environment:
      WORDPRESS_DB_HOST: vulnerable-database
      WORDPRESS_DB_NAME: vulnerable-wordpress
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
    depends_on:
      - vulnerable-database
    networks:
      - test-vn

  vulnerable-database:
    image: mysql:5.5
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: vulnerable-wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    networks:
      - test-vn

  vulnerable-apache:
    platform: linux/amd64
    image: httpd:2.4
    ports:
      - "8081:80"
    networks:
      - test-vn

  wordpress:
    image: wordpress:latest
    ports:
      - "8082:80"
    platform: linux/amd64
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
    depends_on:
      - vulnerable-database
    networks:
      - test-n
  database:
    image: mysql:latest
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3310:3310"
    networks:
      - test-n
  apache:
    platform: linux/amd64
    image: httpd:latest
    ports:
      - "8083:80"
    networks:
      - test-n